# golangci-lint configuration for Throome

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - test/integration
  skip-files:
    - ".*\\.pb\\.go$"

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - gocritic      # Opinionated Go linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Duplicate code detection
    - revive        # Fast, configurable linter

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: var-naming
      - name: package-comments
      - name: error-return
      - name: error-strings
      - name: receiver-naming

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - goconst
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

